[package]
name = "homunculus"
version = "0.1.0"
edition = "2021"

[dependencies]
avian3d = "0.1"
bevy = "0.14"
bevy-inspector-egui = "0.27"
bevy_mod_debugdump = "0.11.1"
leafwing-input-manager = "0.15"
