[package]
name = "homunculus"
version = "0.1.0"
edition = "2021"

[dependencies]
avian3d = "0.2"
bevy = "0.15"
bevy-inspector-egui = "0.28"
bevy_mod_debugdump = "0.12"
leafwing-input-manager = "0.16"
